server:
  port: 9000
  servlet:
    session:
      cookie:
        max-age: 172800

  cloud:
    aws:
      credentials:
        access-key: AKIAW4DFNS65LAGFD66W
        secret-key: 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
      s3: #????
        bucket: snap-rhythm
      region: #S3 ??
        static: ap-northeast-2
      stack:
        auto: false
  # multipartFile ?? ???? ??
  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    #  h2 ??
    h2:
      console:
        enabled: true
    datasource:
      url: jdbc:mysql://database.c1ic8cgmwac9.ap-northeast-2.rds.amazonaws.com:3306/SnapRhythm
      username: admin
      password: !dmssk43
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect
    data:
      web:
        pageable:
          max-page-size: 2000
          default-page-size: 20
          one-indexed-parameters: true
    session:
      store-type: jdbc
      jdbc.initialize-schema: always
      timeout: 86400