    server:
        port: 9000
        servlet:
            session:
                cookie:
                    max-age: 172800
    spring:
        h2:
            console:
                enabled: true
                path: /h2-console
            datasource:
              url: jdbc:h2:~/test
              username: sa
              password:
              driver-class-name: org.h2.Driver
            data:
                web:
                    pageable:
                        max-page-size: 2000
                        default-page-size: 20
                        one-indexed-parameters: true
    session:
        store-type: jdbc
        jdbc.initialize-schema: always
        timeout: 86400

    config:
    jwt-key: "MAmlSvtB7CXj9aBa/5nl/eAk+N34PejDmR7QMP59mnw="