server:
  port: 8761

spring:
  application:
    name: discovery
  security:
    user:
      name: admin
      password: admin

# eureka ? ???? eureka server ? ????? ????.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false